version: "3.9"

services:
  server:
    build: .
    container_name: springboot-server
    ports:
      - "8080:8080"
    environment:
      TODO_MONGO_URI: mongodb://mongo:27017/tododb
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge